## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
matrix:
  include:
    - os: linux
      julia: 0.6
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: 0.7
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: 1.0
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: nightly
      env: TESTCMD="xvfb-run julia"
    - os: osx
      julia: 0.6
      env: TESTCMD="julia"
    - os: osx
      julia: 0.7
      env: TESTCMD="julia"
    - os: osx
      julia: 1.0
      env: TESTCMD="julia"
    - os: osx
      julia: nightly
      env: TESTCMD="julia"
  allow_failures:
    - julia: nightly

notifications:
  email: false

branches:
  only:
    - master

addons:
  apt:
    sources:
      - trusty-media
    packages:
      - ffmpeg

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ffmpeg; fi

script:
 # - julia -e 'Pkg.clone(pwd()); Pkg.build("MeshCat"); Pkg.test("MeshCat"; coverage=true)'
 - $TESTCMD -e 'if VERSION < v"0.7-"; Pkg.clone(pwd()); else; import Pkg; Pkg.add(Pkg.PackageSpec(path=pwd())); end; Pkg.build("MeshCat"); Pkg.test("MeshCat"; coverage=true)'
 - julia --code-coverage=user -e 'using MeshCat; MeshCat.develop_meshcat_assets(true)'
 - julia -e 'if VERSION >= v"0.7-"; import Pkg; end; Pkg.build("MeshCat")'
after_success:
  # push coverage results to Codecov
  - julia -e 'if VERSION >= v"0.7-"; import Pkg; end; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
