## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

branches:
  only:
    - master

addons:
  apt:
    packages:
      - libzmq3
  firefox: latest

env:
  - MOZ_HEADLESS=1

# uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
matrix:
 allow_failures:
 - julia: nightly

before_script:
  - xdg-mime default firefox text/html

after_success:
  - julia -e 'cd(Pkg.dir("MeshCat")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
