## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
matrix:
  include:
    - os: linux
      julia: 0.6
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: 0.7
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: nightly
      env: TESTCMD="xvfb-run julia"
    - os: osx
      julia: 0.6
      env: TESTCMD="julia"
    - os: osx
      julia: 0.7
      env: TESTCMD="julia"
    - os: osx
      julia: nightly
      env: TESTCMD="julia"
  allow_failures:
    - julia: nightly
    - julia: 0.7

notifications:
  email: false
git:
  depth: 99999999

branches:
  only:
    - master

addons:
  apt:
    sources:
      - trusty-media
    packages:
      - ffmpeg

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ffmpeg; fi


script:
 # - julia -e 'Pkg.clone(pwd()); Pkg.build("MeshCat"); Pkg.test("MeshCat"; coverage=true)'
 - $TESTCMD -e 'Pkg.clone(pwd()); Pkg.build("MeshCat"); Pkg.test("MeshCat"; coverage=true)'
 - julia --code-coverage=user -e 'using MeshCat; MeshCat.develop_meshcat_assets(true)'
 - julia -e 'Pkg.build("MeshCat")'
after_success:
  # push coverage results to Coveralls
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("MeshCat")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
